Added Ukrainian(uk_ua) translation
ianm1647/expandeddelight pull request #43
Opened 2023-02-09 23:22 UTC by Voolyk

2023-03-24 14:35 UTC, unroman requested changes

2023-03-24 14:35 UTC, unroman commented on src/main/resources/assets/expandeddelight/lang/uk_ua.json
> +  "item.expandeddelight.peanut_salad": "Салата з арахісом",
Тут помилка "Салат", а не "Салата"

2023-03-29 17:14 UTC, Voolyk commented on src/main/resources/assets/expandeddelight/lang/uk_ua.json
> +  "item.expandeddelight.peanut_salad": "Салата з арахісом",
Дякую, виправив

2023-07-18 10:06 UTC, unroman approved these changes

2023-07-22 15:38 UTC, unroman approved these changes

2023-07-22 15:48 UTC, merged